### ISSUE TITLE
Export as image: Modal padding

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-vis-heatmap#42]
**Current:**
![screen shot 2018-03-08 at 11 18 56 am](https://user-images.githubusercontent.com/30873778/37171688-8923ba78-22c3-11e8-9155-a9f1d78739ac.png)

**Expected:**
![screen shot 2018-03-08 at 11 29 31 am](https://user-images.githubusercontent.com/30873778/37171832-018c360c-22c4-11e8-956b-c9a8d7701259.png)

**Comment by drewharvey** [comment]
@andrealperry is this actually defined in spec?  This modal was only suppose to serve as an example for GE.  It was not intended for use on the actual demo site.

**Comment by andrealperry** [comment]
@drewharvey You're correct. The spec only requires a hook. 

@nonmetalhail @benoitjchevalier do we want to keep this as an issue for internal updates to the demo or just leave it to the application?

**Comment by benoitjchevalier** [comment]
We'll probably remove from demo as it is not demoed on other charts
