### ISSUE TITLE
Key width should be configurable

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-vis-heatmap#43]
Key width should be configurable. Devs should be able to adjust the width to make it thinner or thicker.

Key default:
![screen shot 2018-03-08 at 12 00 39 pm](https://user-images.githubusercontent.com/30873778/37173410-602e7a72-22c8-11e8-8d40-0ed6f0c0bd44.png)

**Comment by drewharvey** [comment]
This can be done by setting the `legendWidth` property in the `legendConfig` object.

```
legendConfig: {
  legendWidth: 100
}
```

Closing - works as expected.
